services:
  - type: web
    name: email-sender-main-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MAIN_BACKEND_VERSION
        value: 1.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*"
    repo: https://github.com/your-username/email-sender-main-backend
    region: oregon
    branch: main
    rootDir: main-backend
    disk:
      name: main-backend-disk
      size: 1